version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "pip"
    directory: "/scripts/update-datasets"
    schedule:
      interval: "weekly"
      day: "saturday"
